eureka:
  client:
    service-url:
      defaultZone: http://euk2.com:8080/eureka/
  instance:
    metadata-map:
      dalao: 自定义


server:
  port: 8081
spring:
  application:
    name: user-consumer-hystrix
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
