eureka:
  client:
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: true
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://euk2.com:7002/eureka/
  instance:
    # eureka节点名称
    hostname: euk1.com
    appname: EurekaServer

  server:
    #关闭自我保护机制
    enable-self-preservation: false
server:
  port: 7001